###############################################################################
#
# packages lists
# roles/packages/vars/main.yml
#
# TODO: combine into a single package list to install
# TODO: missing packages
#
############################################################################### 


---

# missing_packages : packages that must be installed elsewhere as they are not in repo TODO
# packages_archive : archiving programs
# packages_base : always install
# packages_codecs : audio and video codecs and transcoding tools
# packages_customhw : hardware supporting packages for specific machines
# packages_desktop : Only needed on a desktop
# packages_docker : install docker packages
# packages_drawing : for drawing and photo
# packages_extradevel : more dev tools for debugging
# packages_filesystems : filesystem management tools
# packages_fonts : install additionnal fonts
# packages_graphviz : for generating visual graphs
# packages_hardware : general hardware support
# packages_ifwayland : wayland specific packages
# packages_ifxorg : x11 specific packages
# packages_kde : Kde packages
# packages_language : language for correcting
# packages_libreoffice : libre office packages
# packages_multimedia : multimedia packages
# packages_network_client : to access remote files
# packages_publishing : for creating documents
# packages_remote : To facilitate remote connectivity/remote viewing
# packages_scan : for scanning documents
# packages_videoediting : for editing videos


# remove_packages : packages to be removed


missing_packages:
  RedHat:
    - tuptime
    - dfc

packages_archive:
  RedHat:
    #- cabextract
    - bzip2
    - dar
    - gzip
    - lzip
    - lzip
    - p7zip
    - p7zip-plugins
    - pbzip2
    - pigz
    - pxz
    - unrar
    - unzip
    - xz
    - zstd
    
packages_base:
  RedHat:
    - aria2
    - "@base-x"
    - bash-completion
    - bat
    - ca-certificates
    - colordiff
    - "@core"
    - cpio
    - curl
    - dhcp-client
    - dnf-automatic
    - dnf-plugins-core
    - dnf-plugin-system-upgrade
    - dnf-utils
    - dos2unix
    - dstat
    - earlyoom
    - etckeeper
    - expect
    - file
    - findutils
    - fish
    - fpaste
    - git
    - git-extras
    - git-lfs
    - glibc-langpack-en
    - gnupg2
    - "@hardware-support"
    - htop
    - iperf3
    - iproute
    - iproute-tc
    - iputils
    - iputils
    - lshw
    - lsof
    - mbuffer
    - neofetch
    - net-tools
    - nmap
    - openssh-server
    - powertop
    - pv
    - rsync
    - s3fs-fuse
    - screen
    - sudo
    - sysfsutils
    - terminator
    - tmux
    - toolbox
    - traceroute
    - vim-enhanced
    - wireguard-tools
    - wget
    - which
    - whois
    - yum-utils
 

# TODO: Split gui vs no gui    
packages_codecs:
  RedHat:
    - compat-ffmpeg28
    - compat-ffmpeg28-devel
    - ffmpeg
    - ffmpeg-libs
    - ffmpegthumbs
    - gstreamer1-libav
    - gstreamer1-libav
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-base
    - gstreamer1-plugins-base-tools
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-ugly-free
    - gstreamer1-svt-av1
    - gstreamer1-svt-vp9
    - gstreamer1-vaapi
    - gstreamer1-vaapi
    - gstreamer-ffmpeg 
    - intel-media-driver
    - libaacs  
    - libva-devel
    #- libva-intel-driver
    #- libva-intel-hybrid-driver
    - libva-utils
    - libva-vdpau-driver
    - libvdpau-va-gl
    - mencoder
    - youtube-dl

packages_customhw:
  RedHat:
    - apcupsd
    - dymo-cups-drivers

packages_desktop:
  RedHat:
    - android-file-transfer
    - "@Common NetworkManager Submodules"
    - crda
    - "@firefox"
    - "@fonts"
    - gamemode
    - gstreamer1-plugin-openh264
    - iw
    - langpacks-core-font-fr
    - langpacks-core-font-fr
    - langpacks-en
    - langpacks-fr
    - mozilla-openh264
    - NetworkManager-config-connectivity-fedora
    - NetworkManager-wifi
    - pass
    # WIFI FIRMWARE PACKAGE
    - wireless-tools 
    - wpa_supplicant      
    
packages_dev:
  RedHat:
    - "@Developement Tools"
    - "@Devemopement Libraries"
    - bc
    - binutils
    - bison
    - dialog
    - elfutils-libelf-devel
    - flex
    - gcc
    - go
    - kernel-devel
    - kernel-headers
    - kexec-tools
    - make
    - ncurses-devel
    - ncurses-libs
    - openssl-devel
    - perl
    - rust
    - rpm-build
    - rpmdevtools  

              
package_docker:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-compose  
  - docker-engine
  - docker-engine-selinux
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-selinux

        
packages_drawing:
  RedHat:
    - inkscape
    - gimp
    - digicam
    - darktable

packages_extradevel:
  RedHat:
    - stacer
    - bpftrace
    - strace
    
packages_filesystems:
  RedHat:
    - autofs
    - btrfs-progs
    - dosfstools
    - e2fsprogs
    - exfat-utils
    - f2fs-tools
    - fuse
    - fuse-exfat 
    - ntfs-3g-system-compression
    - ntfsprogs
    - xfsprogs
    - xfsdump
    - xfsprogs-xfs_scrub
    - btrfsmaintenance # To configure !      
      
packages_fonts:
  RedHat:
    - adobe-source-code-pro-fonts
    - dejavu-sans-fonts
    - dejavu-sans-mono-fonts
    - dejavu-serif-fonts
    - gnu-free-fonts-common
    - gnu-free-mono-fonts
    - gnu-free-sans-fonts
    - gnu-free-serif-fonts
    - levien-inconsolata-fonts
    - liberation-fonts-common
    - liberation-mono-fonts
    - liberation-sans-fonts
    - liberation-serif-fonts
    - mozilla-fira-mono-fonts
    - msimonson-anonymouspro-fonts
    - overpass-fonts
    - powerline-fonts
    - terminus-fonts
    - wine-fonts

packages_graphviz:
  RedHat:
    - graphviz
    - graphviz-gd
    - graphviz-graphs
    - graphviz-lua
    - graphviz-perl
    - graphviz-tcl
      
packages_hardware:
  RedHat:
    - dmidecode
    - fwupd
    - fwupd-plugin-flashrom
    - hddtemp
    - ipmitool
    - lm_sensors
    - smartmontools
    - powertop   

packages_ifwayland:
  RedHat:
    - wev
    - wl-clipboard

packages_ifxorg:
  RedHat:
    - xclip  
    - xorg-x11-drv-amdgpu 
    
packages_kde:
  RedHat:
    - ark
    - bluedevil
    - breeze-gtk
    - breeze-icon-theme
    - cagibi
    - colord-kde
    - cups-pk-helper
    - dolphin
    - ffmpeg-libs 
    - glibc-all-langpacks
    - gnome-keyring-pam
    - gvfs 
    - gwenview
    - kaccounts-providers
    - kate
    - kate-plugins 
    - kcalc
    - kcm_systemd
    - kdegraphics-thumbnailers
    - kde-gtk-config
    - kde-partitionmanager
    - kdeplasma-addons
    - kde-print-manager
    - kde-settings-pulseaudio
    - kde-style-breeze
    - kdialog
    - kdiff3
    - kdnssd
    - kf5-syntax-highlighting
    - kffmpegthumbnailer 
    - kfind
    - kgpg
    - khotkeys
    - kinfocenter
    - kmenuedit
    - kmouth
    - kmplayer 
    - konsole5
    - kscreen
    - kscreenlocker
    - ksysguard
    - kwalletmanager5
    - kwebkitpart
    - kwin
    - pam-kwallet
    - phonon-qt5-backend-gstreamer
    - plasma-breeze
    - plasma-desktop
    - plasma-desktop-doc
    - plasma-drkonqi
    - plasma-nm
    - plasma-nm-l2tp
    - plasma-nm-openconnect
    - plasma-nm-openswan
    - plasma-nm-openvpn
    - plasma-nm-pptp
    - plasma-nm-ssh
    - plasma-nm-vpnc
    - plasma-pa
    - plasma-user-manager
    - plasma-workspace
    - plasma-workspace-geolocation
    - polkit-kde
    - qt5-qtbase-gui
    - qt5-qtdeclarative
    - sddm
    - sddm-breeze
    - sddm-kcm
    - setroubleshoot
    - sni-qt
    - spectacle
    - system-config-language
    - yakuake
    
packages_language:
  RedHat:
    - aspell-en
    - aspell-fr
    - hunspell-en
    - hunspell-en-US
    - hunspell-fr
    
packages_libreoffice:
  RedHat:
    - "@libreoffice"
    - libreoffice-langpack-en
    - libreoffice-langpack-fr
    - libreoffice-ogltrans
    - libreoffice-opensymbol-fonts
    - libreoffice-pdfimport
    - libreoffice-ure
    - libreoffice-xsltfilter  

packages_multimedia:
  RedHat:
    - audacity
    - clementine
    - handbrake
    - kodi
    - mplayer
    - soundconverter
    - vlc
    - vlc-extras
    - xnconvert
    
packages_network_client:
  RedHat:
    - cifs-utils
    - nfs-utils
    - openldap-clients
    - openssh-clients
    - samba-client
     
packages_publishing:
  RedHat:
    - asciidoctor      
    
packages_remote:
  RedHat:
    - xpra
    #- wireguard-tools
    - tigervnc
    #- kdenetwork-krdc
    #- tigervnc

packages_scan:
  RedHat:
    - gscan2pdf
    - shrinkpdf
    - skanlite
    - ImageMagick
    - GraphicsMagick
    - ghostscript
    - ghostscript-core
    - ghostscript-tools-fonts
    - ghostscript-tools-printing
    # OCR !!
  
packages_videoediting: 
  RedHat:
    - kdenlive
    #- blender
    #- shotcut

packages_virtualization:
   RedHat:
    - "@virtualization"  


# put packages that have dependencies to rpm fusion here
packages_rpmfusion:
  RedHat:
    - dfc
    - tuptime




  



  
remove_packages:
  RedHat:
    - evolution
    - calligra-*
    - evolution-ews
    - evolution-help
    - gnome-classic-session
    - gnome-documents
    - gnome-documents-libs
    - gnome-system-monitor
    - mediawriter
    - mosh
    - plasma-pk-updates 
    - libsss_idmap 
    - libsss_nss_idmap 
    - sssd-client
    - akgregator
    - kget
    - kmail
    - knode
    - konqueror
    - kontact
    #- fprintd # finger print login can cause long wait time to sudo https://bugzilla.redhat.com/show_bug.cgi?id=1534873
  



#_management_packages:
  #all:
    #- chrony
    #- policycoreutils-gui
    #- firewall-config
    #- setools-console
  
#_monitoring_packages:
  #all:
    #- logwatch
    #- fail2ban
    #- collectd
    #- lm_sensors-sensord

#_security_packages:
  #all: 
    #- chkrootkit
    #- inotify-tools
    #- rkhunter

  
## Combining the required packages
  
#admin_packages: "{{ _admin_packages['all'] + ( _admin_packages[os_family] | default([]) ) + ( _admin_packages[distribution] | default([]) ) }}"
#compression_packages: "{{ _compression_packages['all'] + ( _compression_packages[os_family] | default([]) ) + ( _compression_packages[distribution] | default([]) ) }}"
#dev_packages: "{{ _dev_packages['all'] + ( _dev_packages[os_family] | default([]) ) + ( _dev_packages[distribution] | default([]) ) }}"
#docker_packages: "{{ _docker_packages['all'] + ( _docker_packages[os_family] | default([]) ) + ( _docker_packages[distribution] | default([]) ) }}"
#editor_packages: "{{ _editor_packages['all'] + ( _editor_packages[os_family] | default([]) ) + ( _editor_packages[distribution] | default([]) ) }}"
#filesystem_packages: "{{ _filesystem_packages['all'] + ( _filesystem_packages[os_family] | default([]) ) + ( _filesystem_packages[distribution] | default([]) ) }}"
#fonts_packages: "{{ _fonts_packages['all'] + ( _fonts_packages[os_family] | default([]) ) + ( _fonts_packages[distribution] | default([]) ) }}"
#gui_packages: "{{ _gui_packages['all'] + ( _gui_packages[os_family] | default([]) ) + ( _gui_packages[distribution] | default([]) ) }}"
#integrity_packages: "{{ _integrity_packages['all'] + ( _integrity_packages[os_family] | default([]) ) + ( _integrity_packages[distribution] | default([]) ) }}"
#language_packages: "{{ _language_packages['all'] + ( _language_packages[os_family] | default([]) ) + ( _language_packages[distribution] | default([]) ) }}"
#management_packages: "{{ _management_packages['all'] + ( _management_packages[os_family] | default([]) ) + ( _management_packages[distribution] | default([]) ) }}"
#monitoring_packages: "{{ _monitoring_packages['all'] + ( _monitoring_packages[os_family] | default([]) ) + ( _monitoring_packages[distribution] | default([]) ) }}"
#multimedia_packages: "{{ _multimedia_packages['all'] + ( _multimedia_packages[os_family] | default([]) ) + ( _multimedia_packages[distribution] | default([]) ) }}"
#networking_packages: "{{ _networking_packages['all'] + ( _networking_packages[os_family] | default([]) ) + ( _networking_packages[distribution] | default([]) ) }}"
#office_packages: "{{ _office_packages['all'] + ( _office_packages[os_family] | default([]) ) + ( _office_packages[distribution] | default([]) ) }}"
#prereq_packages: "{{ _prereq_packages['all'] + ( _prereq_packages[os_family] | default([]) ) + ( _prereq_packages[distribution] | default([]) ) }}"
#remote-client_packages: "{{ _remote-client_packages['all'] + ( _remote-client_packages[os_family] | default([]) ) + ( _remote-client_packages[distribution] | default([]) ) }}"
#security_packages: "{{ _security_packages['all'] + ( _security_packages[os_family] | default([]) ) + ( _security_packages[distribution] | default([]) ) }}"
#sysutil_packages: "{{ _sysutil_packages['all'] + ( _sysutil_packages[os_family] | default([]) ) + ( _sysutil_packages[distribution] | default([]) ) }}"
#toremove_packages: "{{ _toremove_packages['all'] + ( _toremove_packages[os_family] | default([]) ) + ( _toremove_packages[distribution] | default([]) ) }}"
#utility_packages: "{{ _utility_packages['all'] + ( _utility_packages[os_family] | default([]) ) + ( _utility_packages[distribution] | default([]) ) }}"
  

