###############################################################################
#
# Playbook workstation
# workstation.yml
#
# 21-2-18 Initial version v0.1
#
###############################################################################

---

- name : Fedora workstation playbook
  #hosts: '{{ target }}'
  hosts: FedoraWorkstation
  become: true
  serial: 1
  vars:
    # If there where changes to 
    is_first_run: yes
    rerun_common: yes
    reconfigure_host: no
    reconfigure_repositories: no
    reinstall_packages: no
    reinstall_flatpak: no
    ## Users and groups
    #regular_users:
      #- { name: riux, uid: 1000, groups: "wheel, systemd-journal, riux, steam", password: 'FIXME', homedir: '/home/riux' }
      #- { name: steam, uid: 1100, groups: "steam", password: 'FIXME', homedir: '/home/steam' }
      
    #regular_groups:
      #- { name: riux, gid: 1000,
      #- { name: steam, gid: 1100 } 

    #create_user_groups: yes
    #strick_user_groups: yes # Remove unspecified general users 
    
    # Repositories
    rpmfusion_nonfree: yes
    rpmfusion_free: yes
    # Packages
    base_packages: yes
    # Packages to be combined later
    archive_packages: yes
    codecs_packages: yes
    fonts_packages: yes
    hardware_packages: yes
    kde_packages: yes
    # Flatpack
    flakpack_flathub_enabled: yes
    flakpack_upgrade_all: yes
    flatpak_applications:
      - "com.valvesoftware.Steam"

  #tasks:
    #- name: Write results to logfile
      #blockinfile:
        #create: yes
        #path: "/var/log/ansible/log"
        #insertafter: BOF
        #block: "{{ validate.stdout }}"
        #marker: "# {{ inventory_hostname }} {mark}"
      #delegate_to: localhost
    
  roles:
    - common
      when: is_firts_run | bool or rerun_common | bool
    - configure_host
      when: is_firts_run | bool or reconfigure_host | bool
    - repositories
      when: is_firts_run | bool or reconfigure_repositories | bool
    - packages
      when: is_firts_run | bool or reinstall_packages | bool
    - flatpak
      when: is_firts_run | bool or reinstall_flatpak | bool

# FIX SWAP AND HIBERNATE
# https://superuser.com/questions/1581885/btrfs-luks-swapfile-how-to-hibernate-on-swapfile
