###############################################################################
#
# Playbook workstation
# workstation.yml
#
# 21-2-18 Initial version v0.1
#  TODO: Write a logfile
###############################################################################

---



- name : Fedora workstation playbook
  #hosts: '{{ target }}'
  hosts: workstation
  become: true
  serial: 1

  vars_files:
    - vars/vars.yml

  vars:
    # If there where changes to 
    is_first_run: yes # run every roles 

    # Chose which rore to run 
    role_common: yes 
    role_configure_host: yes
    role_repositories: yes
    role_packages: yes
    role_flatpak: yes
    role_users_groups: yes 
    strick_user_groups: no # Remove unspecified general users TODO
    
    
    # Repositories 
    # marking rpmfusion as no will remove it if it was installed
    rpmfusion_nonfree: yes
    rpmfusion_free: yes

    # Packages
    base_packages: yes

    # Packages to be combined later
    archive_packages: yes
    codecs_packages: yes
    customhw_packages: yes
    desktop_packages: no
    docker_packages: no
    drawing_packages: no
    extradevel_packages: yes
    filesystems_packages: yes
    fonts_packages: yes
    graphviz_packages: no
    hardware_packages: yes
    ifwayland_packages: no
    ifxorg_packages: no
    kde_packages: no
    language_packages: yes
    libreoffice_packages: no
    multimedia_packages: no
    network_client_packages: no
    publishing_packages: no
    remote_packages: no
    scan_packages: no
    videoediting_packages: no

    # Flatpack
    flakpack_flathub_enabled: no 
    flakpack_upgrade_all: no
    flatpak_applications:
      - "com.valvesoftware.Steam"

  tasks:
    - name: Create the log file for this run
      shell: /bin/bash -l -c "mv {{ lookup('env', 'HOME') }}/.ansible/log/ansible.log  {{ lookup('env', 'HOME') }}/.ansible/log/ansible.log-{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
      delegate_to: localhost
      become: yes
      become_user: "{{ lookup('env', 'USER') }}"

  roles:
    - role: common
      when: is_first_run | bool or role_common | bool
    - role: configure_host
      when: is_first_run | bool or role_configure_host | bool
    - role: repositories
      when: is_first_run | bool or role_repositories | bool
    - role: packages
      when: is_first_run | bool or role_packages | bool
    - role: flatpak
      when: role_flatpak | bool
    - role: users
      when: role_users_groups | bool

# FIX SWAP AND HIBERNATE
# https://superuser.com/questions/1581885/btrfs-luks-swapfile-how-to-hibernate-on-swapfile
