###############################################################################
#
# Install base packages
# /roles/packages/task/install_base.yml
#
# 21-2-18 Initial version v0.1
#
###############################################################################

- name: Include rpmfusion vars
  include_vars: vars/main.yml

- name: Install base packages
  dnf:
    name: "{{ packages_base.RedHat }}"
    state: present
  become: yes
  register: dnf_base_result
  when:
    - base_packages | bool
  tags:
    - always
    - install_base_packages
    
    
# TODO
# COMBINE ALL LISTS TO DO A SINGLE INSTALL !! 
    
- name: Install archive packages
  dnf:
    name: "{{ packages_archive.RedHat }}"
    state: present
  become: yes
  register: dnf_archive_result
  when:
    - archive_packages | bool
  tags:
    - always
    - install_archive_packages
    
- name: Install codecs packages
  dnf:
    name: "{{ packages_codecs.RedHat }}"
    state: present
  become: yes
  register: dnf_codecs_result
  when:
    - codecs_packages | bool
  tags:
    - always
    - install_codecs_packages
    
- name: Install fonts packages
  dnf:
    name: "{{ packages_fonts.RedHat }}"
    state: present
  become: yes
  register: dnf_fonts_result
  when:
    - fonts_packages | bool
  tags:
    - always
    - install_fonts_packages
    
- name: Install hardware packages
  dnf:
    name: "{{ packages_hardware.RedHat }}"
    state: present
  become: yes
  register: dnf_hardware_result
  when:
    - hardware_packages | bool
  tags:
    - always
    - install_hardware_packages

- name: Install kde packages
  dnf:
    name: "{{ packages_kde.RedHat }}"
    state: present
  become: yes
  register: dnf_kde_result
  when:
    - kde_packages | bool
  tags:
    - always
    - install_kde_packages
        


    
    
#- debug: Result of base packages install
#    var: dnf_base_result
# TODO: Clean up handler !
    
#- name: Install main packages
  #dnf: name={{ item }} state=latest
  #with_items:
    #- 
