###############################################################################
#
# Install additionnal repositories
# roles/repositories/tasks/main.yml
#
###############################################################################

---

- name: Install rpmfusion repositories for Fedora
  include_tasks: rpmfusion.yml
  when:
    - ansible_distribution in [ "Amazon", "Fedora", "CentOS", "RedHat" ]
  tags:
    - repositories
    - always
    - install_rpmfusion

#TODO UNINSTALL
- name: Uninstall rpmfusion repositories for Fedora
  include_tasks: rpmfusion.yml
  when:
    - ansible_distribution in [ "Amazon", "Fedora", "CentOS", "RedHat" ] and rpmfusion_free | bool == False
    - 
  tags:
    - repositories
    - always
    - uninstall_rpmfusion

