###############################################################################
#
# Common role
# roles/common/tasks/main.yml
#
# 21-2-18 Initial version v0.1
#
###############################################################################

---

- name: Improve DNF Performances
  blockinfile:
    path: /etc/dnf/dnf.conf
    create: yes
    block: |
      deltarpm=true
      fastestmirror=true
      install_weak_deps=false
      max_parallel_downloads={{ ansible_processor_vcpus }}
  become: yes
  tags:
    - first_run
    - always

- name: Upgrade system to latest packages
  include_tasks: update.yml
  tags:
    - upgrade_system
    - always
                
