###############################################################################
#
# Common role
# roles/common/tasks/main.yml
#
# 21-2-18 Initial version v0.1
#
###############################################################################

---
- name: Upgrade system to latest packages
  include: update.yml
  tags:
    - upgrade_system
    - always
                
                
# TODO: Rename system
  # Fix hostname https://serverfault.com/questions/38114/why-does-sudo-command-take-long-to-execute
